<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Schema;

return new class extends Migration
{
    public function up(): void
    {
        // PostGIS-only. The rest of the suite uses in-memory SQLite, which has no
        // geometry types, so skip there instead of breaking it.
        if (DB::getDriverName() !== 'pgsql') {
            return;
        }

        DB::statement('CREATE EXTENSION IF NOT EXISTS postgis');

        Schema::create('survey_polygons', function (Blueprint $table) {
            $table->id();
            // Generated by the client; makes offline sync idempotent.
            $table->uuid('uuid')->unique();
            $table->foreignId('user_id')->constrained('users')->cascadeOnDelete();
            $table->jsonb('raw_points')->nullable();
            $table->double('area_sqm');
            $table->double('perimeter_m');
            $table->unsignedInteger('point_count');
            $table->timestampTz('started_at')->nullable();
            $table->timestampTz('ended_at')->nullable();
            $table->string('source', 20)->default('online'); // online | offline_sync | shp_import
            $table->timestamps();
            $table->softDeletes();

            $table->index(['user_id', 'created_at']);
        });

        DB::statement('ALTER TABLE survey_polygons ADD COLUMN geom geometry(Polygon, 4326) NOT NULL');
        // Raw walked path; null for polygons that came from a shapefile import.
        DB::statement('ALTER TABLE survey_polygons ADD COLUMN track geometry(LineString, 4326)');
        DB::statement('CREATE INDEX survey_polygons_geom_gist ON survey_polygons USING GIST (geom)');
    }

    public function down(): void
    {
        Schema::dropIfExists('survey_polygons');
    }
};
